---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wrike-updater
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: wrike-updater
        spec:
          volumes:
          - name: ga-secrets
            configMap:
              name: ga-secrets-configmap
          containers:
          - name: wrike-updater
            image: registry.ng.bluemix.net/eggshell/wrike-updater:latest
            imagePullPolicy: Always
            command: ["/root/deploy/scripts/run.sh"]
            env:
            - name: WRIKE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wrike-token
                  key: WRIKE_TOKEN
            - name: VIEW_ID
              valueFrom:
                secretKeyRef:
                  name: view-id
                  key: VIEW_ID
            - name: TASK_ID
              valueFrom:
                secretKeyRef:
                  name: task-id
                  key: TASK_ID
            volumeMounts:
            - name: ga-secrets
              mountPath: /var/secrets/google/client_secrets.json
              subPath: client_secrets.json
          restartPolicy: OnFailure
